language: csharp

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild VideoDownloadHelper.sln
  - nunit-console VideoDownloadHelper.Test/bin/Debug/VideoDownloadHelper.Test.dll
notifications:
  email:
    recipients:
      - htynkn@163.com
    on_success:never
    on_failure:always
